# Prefix
unbind F12
unbind C-b
set -g prefix C-x
bind C-x send-prefix

# Terminal quality
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"
set -g focus-events on
set -sg escape-time 10

set -g mode-keys emacs
set -g status-keys emacs

# Usability
set -g mouse on
set -g history-limit 100000
set -g renumber-windows on
setw -g pane-base-index 1
set -g base-index 1

# Splits
bind 3 split-window -h -c "#{pane_current_path}"  # C-x 3
bind 2 split-window -v -c "#{pane_current_path}"  # C-x 2

# Pane navigation: J K I L
bind j select-pane -L
bind k select-pane -D
bind i select-pane -U
bind l select-pane -R

# Reload config
bind r source-file ~/.tmux.conf \; display-message "tmux reloaded"

# Copy mode: Emacs-ish
bind Enter copy-mode
bind -T copy-mode C-s send -X search-forward
bind -T copy-mode C-r send -X search-backward
bind -T copy-mode M-w send -X copy-selection-and-cancel
bind -T copy-mode C-g send -X cancel
